# Generated by Django 3.0.4 on 2020-03-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200304_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='e_to',
            new_name='e',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='n_to',
            new_name='n',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='s_to',
            new_name='s',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='w_to',
            new_name='w',
        ),
        migrations.AddField(
            model_name='room',
            name='background',
            field=models.CharField(default='https://files.slack.com/files-pri/T4JUEB3ME-FUJ7WV4V7/fall_background.jpg', max_length=300),
        ),
        migrations.AddField(
            model_name='room',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='room',
            name='items',
            field=models.CharField(default='Food', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='monster',
            field=models.CharField(default='Fish Monster', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=100),
        ),
    ]
