# Generated by Django 3.0.4 on 2020-03-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200304_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='items',
            new_name='item',
        ),
        migrations.AddField(
            model_name='room',
            name='uuid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='monster',
            field=models.CharField(default='Monster', max_length=50),
        ),
    ]
