# Generated by Django 3.0.4 on 2020-03-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200304_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
