# Generated by Django 3.0.3 on 2020-03-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20200304_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='id',
            new_name='uuid',
        ),
    ]
