# Generated by Django 3.0.4 on 2020-03-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_auto_20200305_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='e_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='n_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='s_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='w_to',
            field=models.IntegerField(default=0),
        ),
    ]
